// <copyright company="SomeCompany" file="RealEstateModel.cs">
// Copyright © Some Company, 2011
// </copyright>
// <auto-generated />
namespace RealEstate.Data
{
    using System;
    using System.Data.Entity;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Linq;

    public partial class RealEstateModel : DbContext
    {
        public RealEstateModel()
            : base("name=RealEstateModel")
        {
        }

        public virtual DbSet<Ingatlan> Ingatlanok { get; set; }
        public virtual DbSet<Szerzodes> Szerzodesek { get; set; }
        public virtual DbSet<Tulajdonos> Tulajdonosok { get; set; }
        public virtual DbSet<Ugyfel> Ugyfelek { get; set; }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Ingatlan>()
                .Property(e => e.Cim)
                .IsUnicode(false);

            modelBuilder.Entity<Ingatlan>()
                .Property(e => e.Tipus)
                .IsUnicode(false);

            modelBuilder.Entity<Ingatlan>()
                .HasMany(e => e.Szerzodes)
                .WithRequired(e => e.Ingatlan)
                .WillCascadeOnDelete(false);

            modelBuilder.Entity<Ingatlan>()
                .HasMany(e => e.Tulajdonos)
                .WithMany(e => e.Ingatlans)
                .Map(m => m.ToTable("Tulajdonol").MapLeftKey("Ing_ID").MapRightKey("Tul_ID"));

            modelBuilder.Entity<Szerzodes>()
                .Property(e => e.Tipus)
                .IsUnicode(false);

            modelBuilder.Entity<Tulajdonos>()
                .Property(e => e.Nev)
                .IsUnicode(false);

            modelBuilder.Entity<Tulajdonos>()
                .Property(e => e.Cim)
                .IsUnicode(false);

            modelBuilder.Entity<Tulajdonos>()
                .Property(e => e.Mobilszam)
                .IsUnicode(false);

            modelBuilder.Entity<Tulajdonos>()
                .Property(e => e.Email)
                .IsUnicode(false);

            modelBuilder.Entity<Ugyfel>()
                .Property(e => e.Nev)
                .IsUnicode(false);

            modelBuilder.Entity<Ugyfel>()
                .Property(e => e.Cim)
                .IsUnicode(false);

            modelBuilder.Entity<Ugyfel>()
                .Property(e => e.Mobilszam)
                .IsUnicode(false);

            modelBuilder.Entity<Ugyfel>()
                .Property(e => e.Email)
                .IsUnicode(false);

            modelBuilder.Entity<Ugyfel>()
                .HasMany(e => e.Szerzodes)
                .WithRequired(e => e.Ugyfel)
                .WillCascadeOnDelete(false);
        }
    }
}
