// <auto-generated/>
namespace RealEstate.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class Szerzodes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "ID")]
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public int Szerzodes_ID { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "ID")]
        public int Ing_ID { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "ID")]
        public int Ugyfel_ID { get; set; }

        [StringLength(20)]
        public string Tipus { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "Ar")]
        public int? Ar { get; set; }

        [Column(TypeName = "date")]
        public DateTime? Datum { get; set; }

        public virtual Ingatlan Ingatlan { get; set; }

        public virtual Ugyfel Ugyfel { get; set; }
    }
}
