// <auto-generated/>
namespace RealEstate.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("Tulajdonos")]
    public partial class Tulajdonos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tulajdonos()
        {
            Ingatlans = new HashSet<Ingatlan>();
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "ID")]
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public int Tul_ID { get; set; }

        [StringLength(20)]
        public string Nev { get; set; }

        [StringLength(70)]
        public string Cim { get; set; }

        [StringLength(10)]
        public string Mobilszam { get; set; }

        [StringLength(40)]
        public string Email { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ingatlan> Ingatlans { get; set; }
    }
}
